tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/php"
tap "homebrew/versions"
tap "homebrew/x11"
tap "olleolleolle/adr-tools"
cask "java"
brew "autoconf"
brew "autojump"
brew "automake"
brew "readline"
brew "bash"
brew "boost"
brew "cookiecutter"
brew "coreutils"
brew "fd"
brew "exa"
brew "lame"
brew "git"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "fzf"
brew "gcc@4.9"
brew "gdbm"
brew "gifsicle"
brew "gist"
brew "git-extras"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "htop-osx"
brew "openssl"
brew "sqlite"
brew "xz"
brew "httpie"
brew "iftop"
brew "libtool"
brew "imagemagick"
brew "iozone"
brew "oniguruma"
brew "jq"
brew "libksba"
brew "libyaml"
brew "lua"
brew "mackup"
brew "mas"
brew "maven"
brew "mongodb"
brew "ngrep"
brew "node"
brew "nvm"
brew "pkg-config"
brew "python"
brew "rename"
brew "ruby"
brew "ssh-copy-id"
brew "tcpflow"
brew "the_silver_searcher"
brew "tree"
brew "vim", args: ["with-override-system-vi"]
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "olleolleolle/adr-tools/adr_tools"
cask "alfred2"
cask "appdelete"
cask "arq"
cask "charles"
cask "dash"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "firefoxdeveloperedition"
cask "github-desktop"
cask "google-chrome"
cask "google-chrome-canary"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "kaleidoscope"
cask "macvim"
cask "mplayerx"
cask "numi"
cask "onyx"
cask "opera"
cask "safari-technology-preview"
cask "sequel-pro"
cask "sketch"
cask "skitch"
cask "slack"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "torbrowser"
cask "tower"
cask "transmit"
cask "tunnelblick"
cask "versions"
cask "visual-studio-code"
cask "vlc"
cask "whatsize"
mas "1Password", id: 443987910
mas "Alternote", id: 974971992
mas "DaisyDisk", id: 411643860
mas "Disk Diag", id: 672206759
mas "GarageBand", id: 682658836
mas "Glyphs Mini", id: 469036911
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Marked", id: 448925439
mas "Navicat Essentials for PostgreSQL", id: 466725643
mas "Numbers", id: 409203825
mas "OmniGraffle", id: 711830901
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
mas "Spark", id: 1176895641
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
mas "xScope", id: 889428659
